[config]
default_to_workspace = false
additional_profiles = ["debug"]

[env]
TARGET_DIR = "target"

[tasks.choose_profile.env]
RUSTFLAGS = "-Copt-level=s"
MODE = "release"
ADDITIONAL = "--release"

    [tasks.choose_profile.env.debug]
    RUSTFLAGS = ""
    MODE = "debug"
    ADDITIONAL = "--profile=dev"


[tasks.build-client]
command = "cargo"
toolchain = "stable"
args = ["build", "-p", "example-client", "--target", "wasm32-unknown-unknown", "${ADDITIONAL}"]
dependencies = ["choose_profile"]

[tasks.copy-static-files]
script_runner = "@duckscript"
script = '''
rm -r ${TARGET_DIR}/web
glob_cp webassets/**/* ${TARGET_DIR}/web/
glob_cp examples/client/webassets/**/* ${TARGET_DIR}/web/
'''

[tasks.deploy-client]
command = "wasm-bindgen"
args = [
    "--target",
    "web",
    "--no-typescript",
    "--out-dir",
    "${TARGET_DIR}/web/dist",
    "--out-name",
    "client",
    "target/wasm32-unknown-unknown/${MODE}/example_client.wasm",
]
dependencies = ["copy-static-files"]

[tasks.client]
dependencies = ["build-client", "deploy-client"]


[tasks.run-server]
command = "cargo"
toolchain = "stable"
args = ["run", "-p", "example-server", "${ADDITIONAL}"]
dependencies = ["choose_profile"]

[tasks.run]
run_task = [
    { name = ["run-server"] },
]
dependencies = ["client"]

[tasks.watch]
command = "watchexec"
args = ["-r", "-w", "examples/client", "cargo", "make", "client"]


[tasks.fmt-check]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--check"]

[tasks.clippy]
toolchain = "stable"
command = "cargo"
args = ["clippy", "--all-targets", "--", "-D", "warnings"]

[tasks.lint]
run_task = [
    { name = ["clippy"] },
]
dependencies = ["fmt-check"]

[tasks.lint-test]
toolchain = "stable"
command = "cargo"
args = ["test"]
dependencies = ["lint"]
